export const ApiPermission = {
  COMPANY_LIST: 'COMPANY.LIST',
  COMPANY_CREATE: 'COMPANY.CREATE',
  COMPANY_UPDATE: 'COMPANY.UPDATE',
  COMPANY_DELETE: 'COMPANY.DELETE',
  OFFICE_LIST: 'OFFICE.LIST',
  OFFICE_CREATE: 'OFFICE.CREATE',
  OFFICE_UPDATE: 'OFFICE.UPDATE',
  OFFICE_DELETE: 'OFFICE.DELETE',
  ROUTE_LIST: 'ROUTE.LIST',
  ROUTE_CREATE: 'ROUTE.CREATE',
  ROUTE_UPDATE: 'ROUTE.UPDATE',
  ROUTE_DELETE: 'ROUTE.DELETE',
  SEAT_MAP_LIST: 'SEAT_MAP.LIST',
  SEAT_MAP_CREATE: 'SEAT_MAP.CREATE',
  SEAT_MAP_UPDATE: 'SEAT_MAP.UPDATE',
  SEAT_MAP_DELETE: 'SEAT_MAP.DELETE',
  SCHEDULE_LIST: 'SCHEDULE.LIST',
  SCHEDULE_CREATE: 'SCHEDULE.CREATE',
  SCHEDULE_UPDATE: 'SCHEDULE.UPDATE',
  SCHEDULE_DELETE: 'SCHEDULE.DELETE',
} as const;

export type ApiPermissionCode =
  (typeof ApiPermission)[keyof typeof ApiPermission];

export const COMPANY_STAFF_PERMISSIONS: ApiPermissionCode[] = [
  ApiPermission.OFFICE_LIST,
  ApiPermission.ROUTE_LIST,
  ApiPermission.SEAT_MAP_LIST,
  ApiPermission.SCHEDULE_LIST,
];

export const COMPANY_ADMIN_PERMISSIONS: ApiPermissionCode[] = [
  ...COMPANY_STAFF_PERMISSIONS,
  ApiPermission.OFFICE_CREATE,
  ApiPermission.OFFICE_UPDATE,
  ApiPermission.OFFICE_DELETE,
  ApiPermission.ROUTE_CREATE,
  ApiPermission.ROUTE_UPDATE,
  ApiPermission.ROUTE_DELETE,
  ApiPermission.SEAT_MAP_CREATE,
  ApiPermission.SEAT_MAP_UPDATE,
  ApiPermission.SEAT_MAP_DELETE,
  ApiPermission.SCHEDULE_CREATE,
  ApiPermission.SCHEDULE_UPDATE,
  ApiPermission.SCHEDULE_DELETE,
];
